"""config.py — Path constants, file creation, and cleanup for envytweaks."""

import logging
import subprocess
from pathlib import Path

# ---------------------------------------------------------------------------
# Path constants
# ---------------------------------------------------------------------------

CACHE_FILE_PATH = Path("/var/cache/envytweaks/cache.json")

BLACKLIST_PATH = Path("/etc/modprobe.d/blacklist-nvidia.conf")
UDEV_INTEGRATED_PATH = Path("/etc/udev/rules.d/50-remove-nvidia.rules")
UDEV_PM_PATH = Path("/etc/udev/rules.d/80-nvidia-pm.rules")
XORG_PATH = Path("/etc/X11/xorg.conf")
EXTRA_XORG_PATH = Path("/etc/X11/xorg.conf.d/10-nvidia.conf")
MODESET_PATH = Path("/etc/modprobe.d/nvidia.conf")
SDDM_XSETUP_PATH = Path("/usr/share/sddm/scripts/Xsetup")
LIGHTDM_SCRIPT_PATH = Path("/etc/lightdm/nvidia.sh")
LIGHTDM_CONFIG_PATH = Path("/etc/lightdm/lightdm.conf.d/20-nvidia.conf")

SUPPORTED_MODES: list[str] = ["integrated", "hybrid", "nvidia"]
SUPPORTED_DISPLAY_MANAGERS: list[str] = ["gdm", "gdm3", "sddm", "lightdm"]
RTD3_MODES: list[int] = [0, 1, 2, 3]

# ---------------------------------------------------------------------------
# File content templates
# ---------------------------------------------------------------------------

BLACKLIST_CONTENT = """\
# Automatically generated by envytweaks

blacklist nouveau
blacklist nova_core
blacklist nova_drm
blacklist nvidia
blacklist nvidia_drm
blacklist nvidia_uvm
blacklist nvidia_modeset
blacklist nvidia_current
blacklist nvidia_current_drm
blacklist nvidia_current_uvm
blacklist nvidia_current_modeset
blacklist i2c_nvidia_gpu
alias nouveau off
alias nova_core off
alias nova_drm off
alias nvidia off
alias nvidia_drm off
alias nvidia_uvm off
alias nvidia_modeset off
alias nvidia_current off
alias nvidia_current_drm off
alias nvidia_current_uvm off
alias nvidia_current_modeset off
alias i2c_nvidia_gpu off
"""

UDEV_INTEGRATED = """\
# Automatically generated by envytweaks

# Remove NVIDIA USB xHCI Host Controller devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x0c0330", ATTR{power/control}="auto", ATTR{remove}="1"

# Remove NVIDIA USB Type-C UCSI devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x0c8000", ATTR{power/control}="auto", ATTR{remove}="1"

# Remove NVIDIA Audio devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x040300", ATTR{power/control}="auto", ATTR{remove}="1"

# Remove NVIDIA VGA/3D controller devices
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x03[0-9]*", ATTR{power/control}="auto", ATTR{remove}="1"
"""

UDEV_PM_CONTENT = """\
# Automatically generated by envytweaks

# Remove NVIDIA USB xHCI Host Controller devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x0c0330", ATTR{remove}="1"

# Remove NVIDIA USB Type-C UCSI devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x0c8000", ATTR{remove}="1"

# Remove NVIDIA Audio devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x040300", ATTR{remove}="1"

# Enable runtime PM for NVIDIA VGA/3D controller devices on driver bind
ACTION=="bind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030000", TEST=="power/control", ATTR{power/control}="auto"
ACTION=="bind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030200", TEST=="power/control", ATTR{power/control}="auto"

# Disable runtime PM for NVIDIA VGA/3D controller devices on driver unbind
ACTION=="unbind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030000", TEST=="power/control", ATTR{power/control}="on"
ACTION=="unbind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030200", TEST=="power/control", ATTR{power/control}="on"
"""

XORG_INTEL = """\
# Automatically generated by envytweaks

Section "ServerLayout"
    Identifier "layout"
    Screen 0 "nvidia"
    Inactive "intel"
EndSection

Section "Device"
    Identifier "nvidia"
    Driver "nvidia"
    BusID "{}"
EndSection

Section "Screen"
    Identifier "nvidia"
    Device "nvidia"
    Option "AllowEmptyInitialConfiguration"
EndSection

Section "Device"
    Identifier "intel"
    Driver "modesetting"
EndSection

Section "Screen"
    Identifier "intel"
    Device "intel"
EndSection
"""

XORG_AMD = """\
# Automatically generated by envytweaks

Section "ServerLayout"
    Identifier "layout"
    Screen 0 "nvidia"
    Inactive "amdgpu"
EndSection

Section "Device"
    Identifier "nvidia"
    Driver "nvidia"
    BusID "{}"
EndSection

Section "Screen"
    Identifier "nvidia"
    Device "nvidia"
    Option "AllowEmptyInitialConfiguration"
EndSection

Section "Device"
    Identifier "amdgpu"
    Driver "amdgpu"
EndSection

Section "Screen"
    Identifier "amd"
    Device "amdgpu"
EndSection
"""

EXTRA_XORG_CONTENT = """\
# Automatically generated by envytweaks

Section "OutputClass"
    Identifier "nvidia"
    MatchDriver "nvidia-drm"
    Driver "nvidia"
"""

FORCE_COMP = '    Option "ForceCompositionPipeline" "true"\n'
COOLBITS_TEMPLATE = '    Option "Coolbits" "{}"\n'

def build_modeset_content(driver: str = "nvidia", rtd3: int | None = None) -> str:
    """Generate modprobe content parameterized by driver name and RTD3 level."""
    base = (
        f"# Automatically generated by envytweaks\n\n"
        f"options {driver}-drm modeset=1\n"
    )
    if rtd3 is not None:
        base += f'options {driver} "NVreg_DynamicPowerManagement=0x0{rtd3}"\n'
    base += f"options {driver} NVreg_UsePageAttributeTable=1 NVreg_InitializeSystemMemoryAllocations=0\n"
    return base


MODESET_CONTENT = build_modeset_content("nvidia")
MODESET_CURRENT_CONTENT = build_modeset_content("nvidia-current")


def build_modeset_rtd3(rtd3_mode: int, driver: str = "nvidia") -> str:
    return build_modeset_content(driver=driver, rtd3=rtd3_mode)


MODESET_RTD3 = build_modeset_content("nvidia", 1)  # Template placeholder
MODESET_CURRENT_RTD3 = build_modeset_content("nvidia-current", 1)

LIGHTDM_CONFIG_CONTENT = """\
# Automatically generated by envytweaks

[Seat:*]
display-setup-script=/etc/lightdm/nvidia.sh
"""

SDDM_XSETUP_CONTENT = """\
#!/bin/sh
# Xsetup - run as root before the login dialog appears

"""

NVIDIA_XRANDR_SCRIPT = """\
#!/bin/sh
# Automatically generated by envytweaks

current=""

xrandr --setprovideroutputsource "{}" NVIDIA-0
xrandr --auto

for next in $(xrandr --listmonitors | grep -E " *[0-9]+:.*" | cut -d" " -f6); do
  [ -z "$current" ] && current=$next && continue
  xrandr --output "$current" --auto --output "$next" --auto --right-of "$current"
  current=$next
done
"""

# ---------------------------------------------------------------------------
# File operations
# ---------------------------------------------------------------------------


def create_file(path: Path, content: str, executable: bool = False, dry_run: bool = False) -> None:
    """Write content to path, creating parent directories as needed."""
    if dry_run:
        exec_str = " (executable)" if executable else ""
        print(f"[DRY-RUN] Would create {path}{exec_str} ({len(content.encode('utf-8'))} bytes)")
        if logging.getLogger().isEnabledFor(logging.DEBUG):
            print(content)
        return

    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        logging.info("Created file %s", path)
        if logging.getLogger().isEnabledFor(logging.DEBUG):
            print(content)
        if executable:
            subprocess.run(["chmod", "+x", str(path)], stdout=subprocess.DEVNULL)
            logging.info("Added execution privilege to %s", path)
    except OSError as e:
        logging.error("Failed to create file '%s': %s", path, e)


def cleanup(dry_run: bool = False) -> None:
    """Remove all config files generated by envytweaks."""
    to_remove: list[Path] = [
        BLACKLIST_PATH,
        UDEV_INTEGRATED_PATH,
        UDEV_PM_PATH,
        XORG_PATH,
        EXTRA_XORG_PATH,
        MODESET_PATH,
        LIGHTDM_SCRIPT_PATH,
        LIGHTDM_CONFIG_PATH,
        # legacy envycontrol paths
        Path("/etc/X11/xorg.conf.d/90-nvidia.conf"),
        Path("/lib/udev/rules.d/50-remove-nvidia.rules"),
        Path("/lib/udev/rules.d/80-nvidia-pm.rules"),
    ]

    for file_path in to_remove:
        if dry_run:
            if file_path.exists():
                print(f"[DRY-RUN] Would remove file {file_path}")
            continue

        try:
            file_path.unlink(missing_ok=True)
            logging.info("Removed file %s", file_path)
        except OSError as e:
            logging.error("Failed to remove file '%s': %s", file_path, e)

    backup_path = Path(str(SDDM_XSETUP_PATH) + ".bak")
    if backup_path.exists():
        if dry_run:
            print(f"[DRY-RUN] Would restore Xsetup backup {backup_path} -> {SDDM_XSETUP_PATH}")
        else:
            logging.info("Restoring Xsetup backup")
            create_file(SDDM_XSETUP_PATH, backup_path.read_text(encoding="utf-8"))
            backup_path.unlink()
            logging.info("Removed file %s", backup_path)
